"""All Common Configurations"""

#APP_CONFIGRATIONS
USE_DATA_FROM_API = True


#OMDB API CONFIGURATIONS
OMDB_API_BASE_URL = "https://www.omdbapi.com"
OMDB_API_QUERY_ENDPOINT = "/"
OMDB_API_QUERY_TITLE_PARAM_NAME = "t"
OMDB_API_QUERY_ID_PARAM_NAME = "i"
OMDB_API_QUERY_TYPE_PARAM_NAME = "type" #movie, series, episode
OMDB_API_QUERY_SEARCH_PARAM_NAME = "s"