"""All Common Configurations"""

# APP_CONFIGRATIONS
USE_FLASK = True
USE_DB_STORAGE = True
USE_MOVIE_API = True

# SQLITE DB CONFIGURATIONS
DB_DIRECTORY = "data"
DB_NAME = "movie_project.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI ='sqlite:///{db_path}'



# OMDB API CONFIGURATIONS
OMDB_API_BASE_URL = "https://www.omdbapi.com"
OMDB_API_QUERY_ENDPOINT = "/"
OMDB_API_QUERY_TITLE_PARAM_NAME = "t"
OMDB_API_QUERY_ID_PARAM_NAME = "i"
OMDB_API_QUERY_TYPE_PARAM_NAME = "type"  # movie, series, episode
OMDB_API_QUERY_SEARCH_PARAM_NAME = "s"
OMDB_API_IMDB_PAGE ="http://www.imdb.com/title/{KEY}"



# HTML CONFIGURATIONS
HTML_DIRECTORY = "_static"
HTML_TEMPLATE_FILE = "index_template.html"
HTML_FILE = "index.html"
HTML_WEB_PAGE_TITLE = "Movie Application"
HTML_TEMPLATE_TITLE_ANCHOR = "__TEMPLATE_TITLE__"
HTML_TEMPLATE_MOVIE_GRID_ANCHOR = "__TEMPLATE_MOVIE_GRID__"

# DATA CONFIGURATIONS
DATA_DIRECTORY = "data"
DATA_FILE = "data.json"
# flag CDN
FLAG_CDN ="https://www.countryflags.io/{KEY}/flat/64.png"
